# Generated by Django 5.2.2 on 2025-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemaPL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        choices=[("max", "Maximizar"), ("min", "Minimizar")],
                        max_length=3,
                    ),
                ),
                ("coef_x1", models.FloatField()),
                ("coef_x2", models.FloatField()),
                ("restricciones", models.JSONField()),
            ],
        ),
    ]
